'use strict';

const REVIEW_SAMPLE_RATE = 48000;
const REVIEW_CHANNELS = 1;
const REVIEW_BITRATE_KBPS = 64;
const ANALYSIS_FRAME_SAMPLES = 480;
const ANALYSIS_HOP_SAMPLES = 480;
const PEAK_BUCKET_SAMPLES = 480;
const ASR_TIMESTAMP_QUANTUM_SECONDS = 0.001;

const TIME_TOLERANCES = Object.freeze({
  integerTicks: 0,
  reviewSampleSeconds: 1 / REVIEW_SAMPLE_RATE,
  analysisBoundarySeconds: ANALYSIS_HOP_SAMPLES / REVIEW_SAMPLE_RATE,
  peakBucketSeconds: PEAK_BUCKET_SAMPLES / REVIEW_SAMPLE_RATE,
  asrFixedOffsetSeconds: Math.max(
    ASR_TIMESTAMP_QUANTUM_SECONDS,
    ANALYSIS_HOP_SAMPLES / REVIEW_SAMPLE_RATE,
  ),
  asrManualWaveformSeconds: Math.max(
    ASR_TIMESTAMP_QUANTUM_SECONDS,
    ANALYSIS_HOP_SAMPLES / REVIEW_SAMPLE_RATE,
  ) + PEAK_BUCKET_SAMPLES / REVIEW_SAMPLE_RATE,
});

module.exports = {
  ANALYSIS_FRAME_SAMPLES,
  ANALYSIS_HOP_SAMPLES,
  ASR_TIMESTAMP_QUANTUM_SECONDS,
  PEAK_BUCKET_SAMPLES,
  REVIEW_BITRATE_KBPS,
  REVIEW_CHANNELS,
  REVIEW_SAMPLE_RATE,
  TIME_TOLERANCES,
};
